server:
  port: 25565 # 원하는 포트 번호로 변경

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql : true
        default_batch_fetch_size: 1000



# 로깅 설정
logging:
  level:
    root: INFO
